### ISSUE TITLE
Ajustar imagen en detalle de Menu

### ISSUE THREAD

**Issue by geronm12** [lourdesgarciafyl/PF-YumYum-frontend#117]
Hola chicos, cómo están? Les dejo este issue un poco más informal puesto que es un fix super sencillo: 
 
 La imagen queda muy pegada a la derecha y si lo pongo responsive la imagen se ve completa 

![image](https://github.com/lourdesgarciafyl/PF-YumYum-frontend/assets/44532299/5fce2b16-f4cf-4e40-9475-8882f09da20f)

![image](https://github.com/lourdesgarciafyl/PF-YumYum-frontend/assets/44532299/c4b92423-e01f-4c77-8fc2-2db33bde3978)

Sólo sería ajustar la imagen para que se vea correcta en modo web

**Comment by cristianq3** [comment]
Correcion realizada en rama: correcionIssues, se ajusta posicion del elemento para que se vea centrado en todos los dispositivos. Muchas gracias.

**Comment by cristianq3** [comment]
Correcion realizada en rama: correcionIssues, se ajusta posicion del elemento para que se vea centrado en todos los dispositivos. Muchas gracias.
