### ISSUE TITLE
Cambiar Label del nombre de usuario

### ISSUE THREAD

**Issue by geronm12** [lourdesgarciafyl/PF-YumYum-frontend#118]
Este es otro issue que les cargo más informal. Más que nada para ayudar al usuario con el tema de el uso del sitio, lo ideal sería que si el nombre de usuario al hacerle click no me va a llevar a su perfil, que directamente sea un label no clickeable (porque esto puede prestar confusión para el usuario)

![image](https://github.com/lourdesgarciafyl/PF-YumYum-frontend/assets/44532299/b2257c6d-ac30-4c0d-bf2b-184ce87c3dc0)

![image](https://github.com/lourdesgarciafyl/PF-YumYum-frontend/assets/44532299/879c1722-ca6e-4648-8afc-9aca04625e45)

**Comment by lourdesgarciafyl** [comment]
Corrección realizada en la rama correccionIssues, se cambia la etiqueta Nav.LInk por ListGroup.Item. Se adapta a perfil cliente y administrador. Muchas gracias!
